name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main  # O la rama que estés usando

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -U jupyter-book
          pip install sphinx_plotly_directive  # Para soportar Plotly

      - name: Build the book
        run: |
          jupyter-book build libro/

      - name: Disable Jekyll
        run: |
          touch libro/_build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./libro/_build/html
          publish_branch: gh-pages